version: '3.3'

volumes:
  pg_data:

services:
  db:
    container_name: scid-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot:
    depends_on:
      - db
    container_name: scid-bot
    #build: .  # раскомментить для работы локально
    image: greenvibe/scid_bot_3  # закомментить для работы локально
    command: bash -c docker_compose_command
    env_file: .env

  gateway:
    depends_on:
      - bot
    container_name: scid-gateway
    image: nginx:1.22.1-alpine
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
